# Generated by Django 5.0 on 2024-01-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_lesson_alter_course_certificate_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
