# Generated by Django 5.0 on 2023-12-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='LEQIIYOWHCKROTVTWUNVTBICO604', max_length=30, primary_key=True, serialize=False),
        ),
    ]
