# Generated by Django 5.0 on 2023-12-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_alter_student_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='LKYJIFAXZEDZSSJAJFPZHCCBJ968', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
