# Generated by Django 5.0 on 2024-01-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_alter_student_student_no_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='JKNLVRIJGLJNTHTKMTLBOKYBH170', max_length=30, primary_key=True, serialize=False),
        ),
    ]
