# Generated by Django 5.0 on 2024-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0009_alter_student_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='TNOIBISFVRUGSDQEGNZYMPDLC823', max_length=30, primary_key=True, serialize=False),
        ),
    ]
