# Generated by Django 5.0 on 2024-01-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0011_alter_student_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='IDWMPFGIDDQLQOEDIGXGPRJPW774', max_length=30, primary_key=True, serialize=False),
        ),
    ]
